// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezthhpxtjqebfvuptxtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dGhocHh0anFlYmZ2dXB0eHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjY2NDgsImV4cCI6MjA3MjA0MjY0OH0.pMbLfMEXe5D7TKfJqx5VM69XNWJFAHmN6T4oQkze_q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});