// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbqlsavrceacxzmcdztp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicWxzYXZyY2VhY3h6bWNkenRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzAyNDgsImV4cCI6MjA3MjMwNjI0OH0.FJKksRG108oQkoDPnUogJt0dTr3Rib5tire5paIVpHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});